-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.employees
(
    employee_id integer NOT NULL,
    first_name character varying(25) NOT NULL,
    last_name character varying(25) NOT NULL,
    nationality_id character varying(11) NOT NULL,
    birth_year integer NOT NULL,
    position_id integer NOT NULL,
    PRIMARY KEY (employee_id)
);

CREATE TABLE public.employers
(
    employer_id integer NOT NULL,
    company_name character varying(25) NOT NULL,
    website character varying(25) NOT NULL,
    phone_number character varying(16) NOT NULL,
    PRIMARY KEY (employer_id)
);

CREATE TABLE public.job_positions
(
    job_id integer NOT NULL,
    name character varying(25) NOT NULL,
    PRIMARY KEY (job_id)
);

CREATE TABLE public.system_staff
(
    staff_id integer NOT NULL,
    first_name character varying(25) NOT NULL,
    last_name character varying(25) NOT NULL,
    PRIMARY KEY (staff_id)
);

CREATE TABLE public.users
(
    id integer NOT NULL,
    email_address character varying(25) NOT NULL,
    password character varying(25) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.employees
    ADD FOREIGN KEY (employee_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employees
    ADD FOREIGN KEY (position_id)
    REFERENCES public.job_positions (job_id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.system_staff
    ADD FOREIGN KEY (staff_id)
    REFERENCES public.users (id)
    NOT VALID;

END;